-- liquibase formatted sql

-- changeset Karachevtsev:1
CREATE TABLE monitors (
    id BIGSERIAL PRIMARY KEY,
    serial_number BIGINT,
    manufacturer VARCHAR(255),
    price INT,
    quantity INT,
    diagonal INT
);


CREATE TABLE жесткие_диски (
    id SERIAL PRIMARY KEY,  -- int8 BIGSERIAL
    серийный_номер BIGINT,
    производитель VARCHAR(255),
    цена INT,
    количество INT,
    память INT
);

CREATE TABLE desktop_computer_entity
(
  id int8 generated by default as identity,
  serial_number int8 NOT NULL,
  manufacturer varchar(255) NOT NULL,
  price int4 NOT NULL,
  quantity int4 NOT NULL,
  form varchar(9) NOT NULL,
  primary key (id)
);

CREATE TABLE laptop_entity
(
  id int8 generated by default as identity,
  serial_number int8 NOT NULL,
  manufacturer varchar(255) NOT NULL,
  price int4 NOT NULL,
  quantity int4 NOT NULL,
  laptop_size varchar(2) NOT NULL,
  primary key (id)
);