-- liquibase formatted sql

-- changeset Karachevtsev:1
CREATE TABLE monitors_entity (
    id BIGSERIAL PRIMARY KEY,
    serial_number BIGINT,
    manufacturer VARCHAR(255),
    price INT  NOT NULL,
    quantity INT  NOT NULL,
    diagonal INT  NOT NULL
);

CREATE TABLE hard_disks_entity (
    id BIGSERIAL PRIMARY KEY,
    serial_number BIGINT,
    manufacturer VARCHAR(255),
    price INT  NOT NULL,
    quantity INT  NOT NULL,
    memory INT  NOT NULL
);

CREATE TABLE desktop_computer_entity
(
  id int8 generated by default as identity,
  serial_number int8 NOT NULL,
  manufacturer varchar(255) NOT NULL,
  price int4 NOT NULL,
  quantity int4 NOT NULL,
  form varchar(9) NOT NULL,
  primary key (id)
);

CREATE TABLE laptop_entity
(
  id int8 generated by default as identity,
  serial_number int8 NOT NULL,
  manufacturer varchar(255) NOT NULL,
  price int4 NOT NULL,
  quantity int4 NOT NULL,
  laptop_size varchar(2) NOT NULL,
  primary key (id)
);

CREATE TABLE user_entity (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    password VARCHAR(20) NOT NULL,
    role VARCHAR(255) NOT NULL
);

ALTER TABLE monitors_entity ADD COLUMN user_id BIGINT;
ALTER TABLE hard_disks_entity ADD COLUMN user_id BIGINT;
ALTER TABLE desktop_computer_entity ADD COLUMN user_id BIGINT;
ALTER TABLE laptop_entity ADD COLUMN user_id BIGINT;

ALTER TABLE monitors_entity ADD CONSTRAINT fk_monitors_user FOREIGN KEY (user_id) REFERENCES user_entity(id);
ALTER TABLE hard_disks_entity ADD CONSTRAINT fk_hard_disks_user FOREIGN KEY (user_id) REFERENCES user_entity(id);
ALTER TABLE desktop_computer_entity ADD CONSTRAINT fk_desktop_computer_user FOREIGN KEY (user_id) REFERENCES user_entity(id);
ALTER TABLE laptop_entity ADD CONSTRAINT fk_laptop_user FOREIGN KEY (user_id) REFERENCES user_entity(id);